spring.application.name=sotexhakaton

# Connection URL - Using localhost because the app runs on your machine, connecting to Docker port 1433
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SotexHackathon;encrypt=true;trustServerCertificate=true

# Credentials from your Docker YAML
spring.datasource.username=sa
spring.datasource.password=SotexSolutions123!

prediction.service.url=http://localhost:8000

# Driver and Dialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl